name: '挂载 WebDAV 存储'
description: '使用 davfs2 挂载 WebDAV 存储服务，支持多平台'
inputs:
  platform:
    description: '目标平台 (ubuntu/macos/windows)'
    required: true
    default: 'ubuntu'
  webdav_url:
    description: 'WebDAV 服务 URL'
    required: true
  username:
    description: 'WebDAV 用户名'
    required: true
  password:
    description: 'WebDAV 密码'
    required: true
  mount_point:
    description: '挂载点路径'
    required: false
    default: '/mnt/share'


runs:
  using: 'composite'
  steps:
    - name: 安装 davfs2 (Ubuntu)
      if: ${{ inputs.platform == 'ubuntu' }}
      shell: bash
      run: |
        sudo apt update && sudo apt install -y davfs2
        sudo mkdir -p ${{ inputs.mount_point }}
        echo "${{ inputs.webdav_url }} ${{ inputs.username }} ${{ inputs.password }}" | sudo tee /etc/davfs2/secrets > /dev/null
        sudo chmod 600 /etc/davfs2/secrets
        echo "use_locks 0" | sudo tee -a /etc/davfs2/davfs2.conf > /dev/null
        sudo mount -t davfs ${{ inputs.webdav_url }} ${{ inputs.mount_point }}
        echo "WebDAV 已挂载到 ${{ inputs.mount_point }}"

    - name: 安装 davfs2 (macOS)
      if: ${{ inputs.platform == 'macos' }}
      shell: bash
      run: |
        echo "暂不支持"

    - name: 安装 davfs2 (Windows)
      if: ${{ inputs.platform == 'windows' }}
      shell: bash
      run: |
        echo "暂不支持"

        

        
