on:
  workflow_run:
    workflows: ["Check Keywords"]  # 监听指定的工作流程
    types:
      - completed  # 当工作流程完成时触发事件

jobs:
  monitor_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check job status
      id: job_status
      run: echo "::set-output name=job_status::${{ github.event.workflow_run.conclusion }}" 
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Rollback on failure
      if: steps.job_status.outputs.job_status == 'failure'  # 如果监测到特定作业失败
      run: |
        ls
        # 回退代码的操作，例如使用 git reset 和 git push 强制推送
        git log
        git reset --soft HEAD~1
        git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用 GitHub Token 进行 Git 操作
