on:
  workflow_run:
    workflows: ["Check Keywords"]  # 监听指定的工作流程
    types:
      - completed  # 当工作流程完成时触发事件

jobs:
  monitor_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check job status
      id: job_status
      run: echo "Job Status:${{ github.event.workflow_run.conclusion }}"
    
    - name: Rollback on failure
      run: |
        for i in ${{ steps.job_status.outputs }};do echo $i ;done
     
