name: Check Keywords

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_keywords:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run keyword check
        run: python check_keywords.py
        
  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Black list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/lwj2048
          dst: gitee/lwj2048
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "scripts"
