name: Bandit Security Scan

on:
  push:
    branches: [ main ] # 只在 main 分支上运行

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # 拉取代码仓库
    - name: Set up Python 3.9 # 配置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies # 安装 Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    - name: Run Bandit # 运行 Bandit
      run: |
        bandit -r .  -x python/ShangGuiGu --exclude "**/*wwwsssxqwertyuioasdfghjklxx*" -s B101 --quiet
