name: PDF to Markdown

on:
  workflow_dispatch:
    inputs:
      pdf_file:
        description: 'PDF 文件名'
        required: true
        default: 'example.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 扩大空间
        uses: ./.github/actions/expand-space
        with:
          platform: 'ubuntu'

      - name: 挂载 Koofr WebDAV (davfs2)
        uses: ./.github/actions/davfs2-mount
        with:
          platform: 'ubuntu'
          webdav_url: 'https://app.koofr.net/dav/Koofr/'
          username: ${{ secrets.KOOFR_USERNAME }}
          password: ${{ secrets.KOOFR_PASSWORD }}
          mount_point: '/mnt/share'
        
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv venv ~/mineru_env
          source ~/mineru_env/bin/activate
          uv pip install -U "mineru[core]"

      - name: Convert PDF with MinerU
        run: |
          source ~/mineru_env/bin/activate
          mkdir -p output/mineru
          sudo cp /mnt/share/pdf/${{ github.event.inputs.pdf_file }} .
          mineru -p ${{ github.event.inputs.pdf_file }}  --output output/mineru/

      # 耗时久，资源开销大
      # - name: Convert PDF with marker-pdf
      #   run: |
      #     pip install marker
      #     mkdir -p output/marker
      #     marker_single  "/mnt/share/pdf/${{ github.event.inputs.pdf_file }}"  --output_format markdown --output_dir output/marker/

      - name: Upload Markdown artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-md
          path: |
            output/mineru
      #     output/marker
