name: Ping Supabase DB

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 2 点运行（北京时间 10 点）
  workflow_dispatch:     # 可手动触发

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9

      - name: Install psycopg2
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Insert random ID to Supabase DB
        env:
          PG_HOST: ${{ secrets.SUPABASE_HOST }}
          PG_PORT: 5432
          PG_DBNAME: postgres
          PG_USER: postgres.zjjllyrxjjsqhemezuwn
          PG_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        run: |
          python -c "import psycopg2, random, os; \
          conn = psycopg2.connect( \
              host=os.getenv('PG_HOST'), \
              port=os.getenv('PG_PORT'), \
              dbname=os.getenv('PG_DBNAME'), \
              user=os.getenv('PG_USER'), \
              password=os.getenv('PG_PASSWORD') \
          ); \
          cur = conn.cursor(); \
          cur.execute('INSERT INTO public.\"Guarantee\" (id) VALUES (%s);', (random.randint(10000, 99999),)); \
          conn.commit(); \
          cur.close(); \
          conn.close(); \
          print('✅ Successfully inserted a random ID.')"
