name: Start SSH Server pCloud

on:
  workflow_dispatch:  # 手动触发

jobs:
  start-ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装 SSH 服务器
        run: |
          sudo apt update && sudo apt install -y openssh-server
          sudo systemctl start ssh
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          # 确保 SSH 目录和权限正确
          sudo mkdir -p /root/.ssh
          sudo chmod 700 /root/.ssh
          # 追加公钥到 authorized_keys
          echo "${{ secrets.ID_RSA_PUB }}" | sudo tee -a /root/.ssh/authorized_keys
          # 设置正确权限
          sudo chmod 600 /root/.ssh/authorized_keys
          sudo chown -R root:root /root/.ssh
      - name: 安装 ngrok 并暴露 SSH 端口
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 22 > /dev/null 2>&1 &  # 暴露 SSH 端口

      - name: 获取 SSH 访问地址
        run: |
          sleep 5
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ssh_address.txt
          echo "🔹 你的 SSH 地址：" $(cat ssh_address.txt)

      - name: 输出 SSH 连接方式
        run: |
          echo "🔹 使用以下命令连接到服务器："
          echo " ssh root@$(cat ssh_address.txt | sed -E 's#tcp://([^:]+):([0-9]+)#\1#') -p $(cat ssh_address.txt | sed -E 's#tcp://([^:]+):([0-9]+)#\2#') "
          sleep 6h
